# Generated by Django 5.1.4 on 2024-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-data_cadastro']},
        ),
        migrations.AddField(
            model_name='produto',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='motivo_retirada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('RETIRADO', 'Retirado')], default='ATIVO', max_length=10),
        ),
    ]
