# Generated by Django 5.1.4 on 2024-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_produto_options_produto_data_retirada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('CONTROLADO', 'Controlado'), ('TERMOLABEL', 'Termolábel'), ('ALIMENTO', 'Alimento'), ('PERFUMARIA', 'Perfumaria')], default='CONTROLADO', max_length=20),
        ),
    ]
