# Generated by Django 5.1.4 on 2024-12-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('PERFUMARIA', 'Perfumaria')], default='MEDICAMENTO', max_length=20),
        ),
    ]
