# Generated by Django 5.1.4 on 2024-12-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('CONTROLADO', 'Controlado'), ('TERMOLABEL', 'Termolábel'), ('ALIMENTO', 'Alimento'), ('PERFUMARIA', 'Perfumaria')], default='MEDICAMENTO', max_length=20),
        ),
    ]
